# Generated by Django 5.1.6 on 2025-03-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_pessoais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#3498db', max_length=7),
        ),
    ]
