# Generated by Django 5.1.6 on 2025-03-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_pessoais', '0002_categoria_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
