# Generated by Django 5.1.6 on 2025-03-05 03:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_pessoais', '0003_conta_descricao_conta_saldo_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tipo', models.CharField(choices=[('E', 'Economia'), ('I', 'Investimento'), ('G', 'Gasto Máximo')], max_length=1)),
                ('periodo', models.CharField(choices=[('M', 'Mensal'), ('T', 'Trimestral'), ('S', 'Semestral'), ('A', 'Anual')], default='M', max_length=1)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas_pessoais.categoria')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas_pessoais.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['data_fim'],
            },
        ),
    ]
