# Generated by Django 5.1.6 on 2025-03-05 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas_pessoais', '0004_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
