# Generated by Django 5.1.6 on 2025-03-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_pessoais', '0006_transacao_data_primeira_parcela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='metodo_pagamento',
            field=models.CharField(choices=[('CC', 'Cartão de Crédito'), ('FI', 'Financiamento'), ('BO', 'Boleto'), ('PI', 'Pix'), ('DI', 'Dinheiro'), ('OU', 'Outros')], default='DI', max_length=2),
        ),
    ]
