# Generated by Django 5.1.6 on 2025-03-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_pessoais', '0007_alter_transacao_metodo_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='observacao',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
