# Generated by Django 5.1.6 on 2025-03-04 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=200)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('data_fundacao', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='ContaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('CI', 'Conta Investimento'), ('CX', 'Caixa'), ('OU', 'Outros')], max_length=2)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas_juridicas.empresa')),
            ],
            options={
                'verbose_name': 'Conta Jurídica',
                'verbose_name_plural': 'Contas Jurídicas',
            },
        ),
        migrations.CreateModel(
            name='CategoriaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas_juridicas.empresa')),
            ],
            options={
                'verbose_name': 'Categoria Jurídica',
                'verbose_name_plural': 'Categorias Jurídicas',
            },
        ),
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('IRPJ', 'Imposto de Renda Pessoa Jurídica'), ('CSLL', 'Contribuição Social sobre o Lucro Líquido'), ('PIS', 'Programa de Integração Social'), ('COFINS', 'Contribuição para o Financiamento da Seguridade Social'), ('ISS', 'Imposto Sobre Serviços'), ('ICMS', 'Imposto sobre Circulação de Mercadorias e Serviços'), ('IPI', 'Imposto sobre Produtos Industrializados'), ('INSS', 'Instituto Nacional do Seguro Social'), ('FGTS', 'Fundo de Garantia do Tempo de Serviço'), ('OUTROS', 'Outros Impostos')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('periodo_referencia', models.CharField(max_length=7)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas_juridicas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imposto',
                'verbose_name_plural': 'Impostos',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa'), ('T', 'Transferência')], max_length=1)),
                ('metodo_pagamento', models.CharField(choices=[('DI', 'Dinheiro'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('BO', 'Boleto'), ('PI', 'Pix'), ('TR', 'Transferência'), ('CH', 'Cheque'), ('OU', 'Outros')], default='DI', max_length=2)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas_juridicas.categoriajuridica')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='financas_juridicas.contajuridica')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_destino', to='financas_juridicas.contajuridica')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas_juridicas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação Jurídica',
                'verbose_name_plural': 'Transações Jurídicas',
                'ordering': ['-data'],
            },
        ),
    ]
