# Generated by Django 5.1.6 on 2025-03-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_juridicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='segmento',
            field=models.CharField(choices=[('COM', 'Comércio'), ('SER', 'Serviços'), ('IND', 'Indústria'), ('TEC', 'Tecnologia'), ('SAU', 'Saúde'), ('EDU', 'Educação'), ('FIN', 'Finanças'), ('OUT', 'Outros')], default='OUT', max_length=3),
        ),
    ]
