# Generated by Django 5.1.6 on 2025-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_juridicas', '0002_empresa_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriajuridica',
            name='cor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
